### ISSUE TITLE
Exception is thrown when generate project is invoked

### ISSUE THREAD

**Issue by dmushkov** [vlingo/vlingo-xoom-starter#2]
[pool-2-thread-6] ERROR io.vlingo.actors.Logger - Exception thrown by Resource execution
io.vlingo.xoom.starter.task.template.TemplateGenerationException: Failed.
	at io.vlingo.xoom.starter.task.steps.StatusHandler.lambda$failureHandling$4(StatusHandler.java:58)
	at io.vlingo.xoom.starter.task.steps.StatusHandler.handle(StatusHandler.java:43)
	at io.vlingo.xoom.starter.task.steps.StatusHandlingStep.process(StatusHandlingStep.java:19)
	at io.vlingo.xoom.starter.task.template.TemplateGenerationManager.lambda$processSteps$1(TemplateGenerationManager.java:26)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.vlingo.xoom.starter.task.template.TemplateGenerationManager.processSteps(TemplateGenerationManager.java:26)
	at io.vlingo.xoom.starter.task.template.TemplateGenerationManager.run(TemplateGenerationManager.java:20)
	at io.vlingo.xoom.starter.task.Task.run(Task.java:44)
	at io.vlingo.xoom.starter.task.TaskExecutor.execute(TaskExecutor.java:19)
	at io.vlingo.xoom.starter.restapi.GenerationSettingsResource.lambda$startGeneration$0(GenerationSettingsResource.java:26)
	at io.vlingo.common.BasicCompletes$Executables.executeActions(BasicCompletes.java:478)
	at io.vlingo.common.BasicCompletes$Executables.registerWithExecution(BasicCompletes.java:436)
	at io.vlingo.common.BasicCompletes$BasicActiveState.registerWithExecution(BasicCompletes.java:852)
	at io.vlingo.common.BasicCompletes.andThenConsume(BasicCompletes.java:92)
	at io.vlingo.common.BasicCompletes.andThenConsume(BasicCompletes.java:108)
	at io.vlingo.xoom.starter.restapi.GenerationSettingsResource.startGeneration(GenerationSettingsResource.java:26)
	at io.vlingo.http.resource.RequestHandler1.lambda$null$0(RequestHandler1.java:57)
	at io.vlingo.http.resource.RequestExecutor.executeRequest(RequestExecutor.java:25)
	at io.vlingo.http.resource.RequestHandler1.lambda$handle$1(RequestHandler1.java:57)
	at io.vlingo.http.resource.RequestHandler1.lambda$execute$4(RequestHandler1.java:78)
	at io.vlingo.http.resource.RequestExecutor.executeRequest(RequestExecutor.java:25)
	at io.vlingo.http.resource.RequestHandler1.lambda$execute$5(RequestHandler1.java:80)
	at io.vlingo.http.resource.RequestHandler.runParamExecutor(RequestHandler.java:62)
	at io.vlingo.http.resource.RequestHandler1.execute(RequestHandler1.java:80)
	at io.vlingo.http.resource.RequestHandler1.execute(RequestHandler1.java:87)
	at io.vlingo.http.resource.ResourceRequestHandlerActor.lambda$handleFor$3(ResourceRequestHandlerActor.java:45)
	at io.vlingo.http.resource.ResourceRequestHandlerActor.handleFor(ResourceRequestHandlerActor.java:31)
	at io.vlingo.http.resource.ResourceRequestHandlerActor.handleFor(ResourceRequestHandlerActor.java:51)
	at io.vlingo.http.resource.ResourceRequestHandler__Proxy.lambda$handleFor$e376e271$1(ResourceRequestHandler__Proxy.java:46)
	at io.vlingo.actors.LocalMessage.internalDeliver(LocalMessage.java:121)
	at io.vlingo.actors.LocalMessage.deliver(LocalMessage.java:53)
	at io.vlingo.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by danilo-ambrosio** [comment]
@dmushkov 
I need two more details:

1. Could you please also send me the `vlingo-xoom-starter.properties`  placed under the `starter` home directory? 

2. In addition, please confirm if you've executed `xoom gen`  command in that scenario.

Thanks in advance!

**Comment by dmushkov** [comment]
Hm .. ok 
1) I run xoom gen with default **vlingo-xoom-starter.properties** 
2) I try generation through xoom gui - now it's working ... I notice some dependencies were download during step 1) ...

**Comment by danilo-ambrosio** [comment]
Thanks for the details, @dmushkov.

I'll reach out to you when it's fixed.

**Comment by danilo-ambrosio** [comment]
I've noticed there was a typo in the default properties file and fixed that. Please consider the new **vlingo-xoom-starter.propeties** version in the master branch. 

Additionally, ensure that the informed target folder actually exists.

Looking forward to your reply.

Thanks

**Comment by danilo-ambrosio** [comment]
Clarifying, in regard to dependencies download, this is a maven archetypes process. No worries, that's expected behavior.

Also, if you want to generate a project, you may also use `xoom gui` or `xoom gen`. Both are alternative ways for a quick start with xoom. The latter reads parameters from a properties file, the first consumes parameters from web-based UI.

**Comment by danilo-ambrosio** [comment]
@dmushkov 
Any update on that issue?

**Comment by dmushkov** [comment]
@danilo-ambrosio unfortunate I can not reproduce this behaviour any more

**Comment by VaughnVernon** [comment]
@dmushkov That sound like fortunate news to me :smiley: Thanks for confirming the fix!

**Comment by danilo-ambrosio** [comment]
@dmushkov I'm gonna close this issue, right?

Any future questions,  we're available to help.
